#!/bin/bash

# email_meeting_prep.sh
# Usage: ./email_meeting_prep.sh "Contact Name"
# Wrapper to generate the report and email it instead of opening it.

cd "$(dirname "$0")" || exit 1

# 1. Config
WEB_APP_URL="https://script.google.com/macros/s/AKfycbxhH0lpZ3tq6KZovVQV8UpJubi74EloknJRQzYfDiV7yfAr585sdw_OGNPzCMkzjAlG/exec"
QUERY="$1"

if [ -z "$QUERY" ]; then
    echo "Usage: ./email_meeting_prep.sh \"Name or Email\""
    echo "Example: ./email_meeting_prep.sh \"Luke Minto\""
    exit 1
fi

echo "--- Generating Meeting Prep for: $QUERY ---"

# 2. Run the Generator (meeting_prep.sh)
# Logic taken from MeetingPrep.command but simplified for headless execution
TOKEN_FILE=".recent_token"
OPENAI_KEY_FILE=".openai_key"

# Ensure Token
if [ -f "$TOKEN_FILE" ]; then
    TOKEN=$(cat "$TOKEN_FILE")
else
    # Try to get one if missing
    if ./get_token.sh --silent; then
        TOKEN=$(cat "$TOKEN_FILE")
    else
        echo "[-] Error: No token found. Run ./get_token.sh first."
        exit 1
    fi
fi

# Ensure OpenAI Key
if [ -f "$OPENAI_KEY_FILE" ]; then
    OPENAI_KEY=$(cat "$OPENAI_KEY_FILE")
else
    OPENAI_KEY=""
fi

# Generate Report to temporary file
OUTPUT_FILE="/tmp/meeting_prep_raw.txt"
./meeting_prep.sh "$QUERY" "$TOKEN" "$OPENAI_KEY" > "$OUTPUT_FILE"

# Check for success
if grep -q "MEETING PREPARATION BRIEF:" "$OUTPUT_FILE"; then
    echo "[+] Report generated successfully."
else
    echo "[-] Error: Failed to generate report. Raw output:"
    cat "$OUTPUT_FILE"
    exit 1
fi

# 3. Format into HTML for Email
# We'll re-use the "MeetingPrep.command" logic to wrap it in a nice HTML template
HTML_FILE="/tmp/Meeting_Report.html"
DATE_STR=$(date)

# Extract Metadata (Quick regex/grep extraction)
NAME=$(grep "Subject:" "$OUTPUT_FILE" | head -n 1 | sed 's/Subject: //')
[ -z "$NAME" ] && NAME="$QUERY"

# Construct HTML Wrapper (Simplified styling for email clients)
cat <<EOF > "$HTML_FILE"
<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: Helvetica, Arial, sans-serif; padding: 20px; line-height: 1.5; color: #333; }
    .card { border: 1px solid #ddd; background: #fff; padding: 20px; border-radius: 8px; margin-bottom: 20px; }
    h1 { color: #1f6feb; border-bottom: 1px solid #ddd; padding-bottom: 10px; }
    h2 { font-size: 16px; color: #555; text-transform: uppercase; margin-top: 20px; border-bottom: 1px solid #eee; }
    .footer { font-size: 12px; color: #999; margin-top: 30px; text-align: center; }
    pre { white-space: pre-wrap; font-family: inherit; } 
  </style>
</head>
<body>
  <div class="card">
    <h1>Meeting Prep: $NAME</h1>
    <pre>$(cat "$OUTPUT_FILE")</pre>
  </div>
  <div class="footer">Generated by Antigravity VPS at $DATE_STR</div>
</body>
</html>
EOF

# 4. Email the Report
echo "[*] Sending Email via Google Web App..."

# Read HTML Content
HTML_CONTENT=$(cat "$HTML_FILE")

# Create JSON payload
PAYLOAD=$(jq -n --arg html "$HTML_CONTENT" --arg subj "Meeting Prep: $NAME" '{html: $html, subject: $subj}')

# POST
RESPONSE=$(curl -L -s -X POST -H "Content-Type: application/json" -d "$PAYLOAD" "$WEB_APP_URL")

echo "Email Status: $RESPONSE"
echo "Done."
